services:
  - type: web
    name: lunova-api
    env: python
    buildCommand: cd blazingfast-api && pip install -r requirements.txt
    startCommand: cd blazingfast-api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_URL
        sync: false
      - key: VITE_OPENWEATHER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_API_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: PPLX_API_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
