import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  changeLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.collections': 'Collections',
    'nav.pricing': 'Pricing',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.shop': 'Shop',
    'nav.account': 'Account',
    'nav.users': 'Users',
    'nav.products': 'Products',
    'nav.analytics': 'Analytics',
    'nav.blogs': 'Blogs',
    'nav.tickets': 'Tickets',
    
    // Hero
    'hero.badge': 'Premium Jewelry & Souvenirs',
    'hero.title.line1': 'Jewelry.',
    'hero.title.line2': 'Souvenirs.',
    'hero.title.line3': 'Stories.',
    'hero.description': 'A curated space for meaningful items that celebrate memories and connections.',
    'hero.cta.getStarted': 'Let\'s Start',
    'hero.cta.consultation': 'Book Consultation',
    'hero.stats.customers': 'Happy Customers',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.award': 'Award Winner',
    'hero.stats.design': 'Design Excellence',
    'hero.price.from': 'Starting from',
    
    // Authentication
    'auth.login': 'Sign In',
    'auth.loginDescription': 'Sign in to your Lunova account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loggingIn': 'Signing in...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signUp': 'Sign up',
    'auth.signUpDescription': 'Create a new account to join Lunova',
    'auth.createAccount': 'Create Account',
    'auth.registerDescription': 'Join the Lunova family today',
    'auth.name': 'Full name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.creating': 'Creating account...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDescription': 'Enter your email and we\'ll send you a link to reset your password',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.sending': 'Sending...',
    'auth.resetEmailSent': 'Password reset email sent. Please check your inbox.',
    'auth.backToLogin': 'Back to login',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.accountOptions': 'Account Options',
    'auth.forgotPasswordDescription': 'Enter your email and we\'ll send you a link to reset your password',
    'auth.secureLogin': 'Secure login with Supabase',
    'auth.loginFailed': 'Login failed. Please check your credentials.',
    'auth.unexpectedError': 'An unexpected error occurred. Please try again.',
    'auth.fieldsRequired': 'All fields are required.',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to your account to continue',
    
    // Dashboard
    'dashboard.create': 'Create',
    'dashboard.dashboard': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Manage your jewelry collection and orders',
    'dashboard.logout': 'Logout',
    'dashboard.stats.orders': 'Total Orders',
    'dashboard.stats.favorites': 'Favorites',
    'dashboard.stats.cart': 'Cart Items',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.orderDate': 'Order Date',
    'dashboard.newOrder': 'New Order',
    'dashboard.favorites': 'Favorites',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    'dashboard.userManagement': 'User Management',
    'dashboard.users': 'users',
    'dashboard.searchUsers': 'Search users...',
    'dashboard.sortingBy': 'Sorting By',
    'dashboard.filters': 'Filters',
    'dashboard.userName': 'User Name',
    'dashboard.emailAddress': 'Email Address',
    'dashboard.city': 'City',
    'dashboard.createdAt': 'Created at',
    'dashboard.actions': 'Actions',
    'dashboard.previous': 'Previous',
    'dashboard.next': 'Next',
    'dashboard.stats.activeUsers': 'Active Users',
    'dashboard.stats.newUsers': 'New Users',
    'dashboard.stats.totalUsers': 'Total Users',
    'dashboard.stats.comparedTo': 'compared to last month',
    'dashboard.products.title': 'Products',
    'dashboard.products.items': 'items',
    'dashboard.products.allShops': 'All Shops',
    'dashboard.products.searchProducts': 'Search products...',
    'dashboard.products.addProduct': 'Add Product',
    'dashboard.products.productName': 'Product Name',
    'dashboard.products.category': 'Category',
    'dashboard.products.price': 'Price',
    'dashboard.products.stock': 'Stock',
    'dashboard.products.status': 'Status',
    'dashboard.products.showing': 'Showing',
    'dashboard.products.to': 'to',
    'dashboard.products.of': 'of',
    'dashboard.products.results': 'results',
    'dashboard.tickets.title': 'Support Tickets',
    'dashboard.tickets.items': 'tickets',
    'dashboard.tickets.searchTickets': 'Search tickets...',
    'dashboard.tickets.createTicket': 'Create Ticket',
    'dashboard.tickets.ticketId': 'Ticket ID',
    'dashboard.tickets.subject': 'Subject',
    'dashboard.tickets.customer': 'Customer',
    'dashboard.tickets.status': 'Status',
    'dashboard.tickets.priority': 'Priority',
    'dashboard.tickets.created': 'Created',
    'dashboard.tickets.updated': 'Updated',
    'dashboard.tickets.showing': 'Showing',
    'dashboard.tickets.to': 'to',
    'dashboard.tickets.of': 'of',
    'dashboard.tickets.results': 'results',
    'dashboard.loading': 'Loading...',
    'dashboard.error': 'Error',
    'dashboard.success': 'Success',
    'dashboard.warning': 'Warning',
    'dashboard.info': 'Info',
    'dashboard.filter': 'Filter',
    'dashboard.totalShops': 'Total Shops',
    'dashboard.totalProducts': 'Total Products',

    // Shop Management
    'nav.shops': 'Shops',
    'dashboard.shops': 'Shop Management',
    'dashboard.createShop': 'Create Shop',
    'dashboard.editShop': 'Edit Shop',
    'dashboard.deleteShop': 'Delete Shop',
    'dashboard.shopName': 'Shop Name',
    'dashboard.shopDescription': 'Description',
    'dashboard.shopContact': 'Contact',
    'dashboard.shopAddress': 'Address',
    'dashboard.shopBusinessHours': 'Business Hours',
    'dashboard.shopSocialMedia': 'Social Media',
    'dashboard.shopVerified': 'Verified',
    'dashboard.shopOwner': 'Owner',
    'dashboard.shopCreatedAt': 'Created At',
    'dashboard.shopUpdatedAt': 'Updated At',
    'dashboard.searchShops': 'Search shops...',
    'dashboard.noShopsFound': 'No shops found',
    'dashboard.confirmDeleteShop': 'Are you sure you want to delete this shop?',
    'dashboard.shopDeleted': 'Shop deleted successfully',
    'dashboard.shopDeleteError': 'Error deleting shop',
    'dashboard.verificationStatus': 'Verification Status',
    'dashboard.verified': 'Verified',
    'dashboard.unverified': 'Unverified',
    'dashboard.cancel': 'Cancel',
    'dashboard.saveChanges': 'Save Changes',
    'dashboard.createShopDescription': 'Fill in the details to create your shop',
    'dashboard.editShopDescription': 'Edit your shop details below',
    'dashboard.basicInformation': 'Basic Information',
    'dashboard.media': 'Media',
    'dashboard.logoUrl': 'Logo URL',
    'dashboard.bannerUrl': 'Banner URL',
    'dashboard.contactInformation': 'Contact Information',
    'dashboard.contactEmail': 'Email',
    'dashboard.phone': 'Phone',
    'dashboard.noContactInfo': 'No contact information',
    'dashboard.streetAddress': 'Street Address',
    'dashboard.state': 'State/Province',
    'dashboard.country': 'Country',
    'dashboard.postalCode': 'Postal Code',
    'dashboard.website': 'Website',
    'dashboard.created': 'Created',
    'dashboard.errorDeletingShop': 'Error deleting shop. Please try again later.',
    // Product Dashboard
    'dashboard.products.editProduct': 'Edit Product',
    'dashboard.products.inStock': 'In Stock',
    'dashboard.products.lowStock': 'Low Stock',
    'dashboard.products.outOfStock': 'Out of Stock',
    'dashboard.products.noProducts': 'No products available. Create your first product!',
    'dashboard.products.noProductsFound': 'No products found matching your search.',
    'dashboard.products.createProductDescription': 'Fill in the details to create a new product.',
    'dashboard.products.editProductDescription': 'Update your product information below.',
    'dashboard.products.selectShop': 'Select Shop',
    'dashboard.products.selectShopPlaceholder': 'Select a shop...',
    'dashboard.products.name': 'Product Name',
    'dashboard.products.description': 'Description',
    'dashboard.products.pricing': 'Pricing',
    'dashboard.products.salePrice': 'Sale Price',
    'dashboard.products.additionalDetails': 'Additional Details',
    'dashboard.products.subcategory': 'Subcategory',
    'dashboard.products.material': 'Material',
    'dashboard.products.physicalAttributes': 'Physical Attributes',
    'dashboard.products.weight': 'Weight (g)',
    'dashboard.products.dimensions': 'Dimensions',
    'dashboard.products.inventory': 'Inventory',
    'dashboard.products.stockQuantity': 'Stock Quantity',
    'dashboard.products.productFlags': 'Product Flags',
    'dashboard.products.isFeatured': 'Featured',
    'dashboard.products.isNew': 'New',
    'dashboard.products.isOnSale': 'On Sale',
    'dashboard.errorFetchingProducts': 'Error fetching products. Please try again later.',
    'dashboard.errorSavingProduct': 'Error saving product. Please try again later.',
    'dashboard.errorDeletingProduct': 'Error deleting product. Please try again later.',
    'dashboard.confirmDeleteProduct': 'Are you sure you want to delete this product?',
    'dashboard.selectShop': 'Please select a shop for this product',
    'dashboard.errorSavingShop': 'Error saving shop. Please try again later.',
    'dashboard.shopLocation': 'Shop Locations',
    'dashboard.shopCreated': 'Shop Creation',
    'dashboard.shopUpdated': 'Shop Update',
    'dashboard.shopActions': 'Shop Actions',
    
    // Market Insights
    'dashboard.marketInsights': 'Market Insights',
    'dashboard.marketInsights.marketSize': 'Market Size',
    'dashboard.marketInsights.growthRate': 'Growth Rate',
    'dashboard.marketInsights.keyPlayers': 'Key Players',
    'dashboard.marketInsights.recentDevelopments': 'Recent Developments',
    'dashboard.marketInsights.consumerInsights': 'Consumer Insights',
    'dashboard.marketInsights.averagePrice': 'Average Price',
    'dashboard.marketInsights.priceTrend': 'Price Trend',
    'dashboard.marketInsights.error': 'Failed to load market insights. Please try again later.',
    'dashboard.marketInsights.noInsights': 'No insights available. Please select a category.',
    'dashboard.marketInsights.categories.jewelry': 'Jewelry',
    'dashboard.marketInsights.categories.gasoline': 'Gasoline',
    'dashboard.marketInsights.categories.electronics': 'Electronics',
    'dashboard.marketInsights.categories.fashion': 'Fashion',
    'dashboard.marketInsights.categories.homeDecor': 'Home Decor',
    'common.loading': 'Loading...',
    'common.refresh': 'Refresh',

    // Settings Modal
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.account': 'Account',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.autoSave': 'Auto-save changes',
    'settings.analytics': 'Share analytics',
    'settings.changePassword': 'Change Password',
    'settings.twoFactor': 'Two-factor Authentication',
    'settings.connectedAccounts': 'Connected Accounts',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.marketingEmails': 'Marketing Emails',
    'settings.dataSaving': 'Data Saving',
    'settings.cookies': 'Cookie Preferences',
    'settings.dataExport': 'Export Your Data',
    'settings.darkMode': 'Dark Mode',
    'settings.theme': 'Theme',
    
    // Services
    'services.title': 'Our Services',
    'services.description': 'From custom designs to expert repairs, we offer comprehensive jewelry services to bring your vision to life and maintain your precious pieces.',
    'services.custom.title': 'Custom Jewelry Design',
    'services.custom.description': 'Create unique pieces tailored to your vision with our expert craftsmen.',
    'services.custom.feature1': '3D Design Preview',
    'services.custom.feature2': 'Material Selection',
    'services.custom.feature3': 'Lifetime Warranty',
    'services.restoration.title': 'Jewelry Restoration',
    'services.restoration.description': 'Breathe new life into your cherished pieces with professional restoration.',
    'services.restoration.feature1': 'Antique Restoration',
    'services.restoration.feature2': 'Stone Replacement',
    'services.restoration.feature3': 'Metal Refinishing',
    'services.repair.title': 'Repair Services',
    'services.repair.description': 'Expert repair services to keep your jewelry looking perfect.',
    'services.repair.feature1': 'Ring Sizing',
    'services.repair.feature2': 'Chain Repair',
    'services.repair.feature3': 'Clasp Replacement',
    'services.wedding.title': 'Wedding Collections',
    'services.wedding.description': 'Special moments deserve special jewelry for your big day.',
    'services.wedding.feature1': 'Engagement Rings',
    'services.wedding.feature2': 'Wedding Bands',
    'services.wedding.feature3': 'Bridal Sets',
    'services.luxury.title': 'Luxury Pieces',
    'services.luxury.description': 'Exclusive high-end jewelry for the most discerning clients.',
    'services.luxury.feature1': 'Precious Stones',
    'services.luxury.feature2': 'Platinum Setting',
    'services.luxury.feature3': 'Certified Authenticity',
    'services.souvenirs.title': 'Unique Souvenirs',
    'services.souvenirs.description': 'Memorable keepsakes and gifts for every special occasion.',
    'services.souvenirs.feature1': 'Personalized Engraving',
    'services.souvenirs.feature2': 'Gift Packaging',
    'services.souvenirs.feature3': 'Custom Boxes',
    
    // Collections
    'collections.title': 'Our Collections',
    'collections.description': 'Explore our carefully curated collections, each telling its own story through exceptional craftsmanship and timeless design.',
    'collections.diamond.title': 'Diamond Elegance',
    'collections.diamond.description': 'Timeless diamond pieces that capture eternal beauty',
    'collections.pearl.title': 'Pearl Classics',
    'collections.pearl.description': 'Sophisticated pearl jewelry for the modern woman',
    'collections.gold.title': 'Gold Heritage',
    'collections.gold.description': 'Handcrafted gold pieces with traditional artistry',
    'collections.modern.title': 'Modern Minimalist',
    'collections.modern.description': 'Clean lines and contemporary design for everyday wear',
    'collections.vintage.title': 'Vintage Treasures',
    'collections.vintage.description': 'Carefully curated vintage pieces with history',
    'collections.custom.title': 'Custom Creations',
    'collections.custom.description': 'Bespoke jewelry designed just for you',
    'collections.view': 'View Collection',
    'collections.viewAll': 'View All Collections',
    'collections.from': 'From',
    
    // Pricing
    'pricing.title': 'Choose Your Plan',
    'pricing.description': 'Whether you\'re a jewelry enthusiast or a business owner, we have the perfect plan to meet your needs.',
    'pricing.forBuyers': 'For Buyers',
    'pricing.forShopOwners': 'For Shops',
    'pricing.basic.name': 'Basic Explorer',
    'pricing.basic.description': 'Perfect for discovering and trying jewelry',
    'pricing.premium.name': 'Premium Collector',
    'pricing.premium.description': 'Ideal for serious jewelry enthusiasts',
    'pricing.business.name': 'Business Pro',
    'pricing.business.description': 'Complete solution for jewelry businesses',
    'pricing.enterprise.name': 'Enterprise Scale',
    'pricing.enterprise.description': 'Advanced solution for large jewelry chains',
    'pricing.popular': 'Most Popular',
    'pricing.perPiece': 'per piece',
    'pricing.getStarted': 'Get Started',
    'pricing.bulkQuote': 'Need a custom quote for bulk orders?',
    'pricing.contactSales': 'Contact Our Sales Team',
    
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.description': 'Don\'t just take our word for it. Here\'s what our satisfied customers have to say about their Lunova experience.',
    'testimonials.rating': 'Average Rating',
    'testimonials.reviews': 'Reviews',
    'testimonials.satisfaction': 'Satisfaction Rate',
    
    // Contact
    'contact.title': 'Get In Touch',
    'contact.description': 'Ready to create something beautiful? Let\'s discuss your vision and bring your dream jewelry to life.',
    'contact.info': 'Contact Information',
    'contact.visit': 'Visit Our Showroom',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.hours': 'Business Hours',
    'contact.schedule': 'Schedule a Consultation',
    'contact.scheduleDesc': 'Book a private consultation with our expert designers to discuss your project in detail.',
    'contact.bookAppointment': 'Book Appointment',
    'contact.sendMessage': 'Send Us a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.service': 'Service',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us about your project...',
    'contact.form.send': 'Send Message',
    'contact.form.selectService': 'Select a service',
    'contact.form.customDesign': 'Custom Design',
    'contact.form.restoration': 'Restoration',
    'contact.form.repair': 'Repair',
    'contact.form.consultation': 'Consultation',
    
    // Footer
    'footer.description': 'Creating timeless jewelry and precious memories since 1998. Every piece tells a story, crafted with passion and precision.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contactInfo': 'Contact Info',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterPlaceholder': 'Your email',
    'footer.copyright': '© 2025 Lunova Co. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.shipping': 'Shipping & Returns'
  },
  ja: {
    // Header
    'nav.home': 'ホーム',
    'nav.services': 'サービス',
    'nav.collections': 'コレクション',
    'nav.pricing': '料金',
    'nav.reviews': 'レビュー',
    'nav.contact': 'お問い合わせ',
    'nav.shop': 'ショップ',
    'nav.account': 'アカウント',
    'nav.users': 'ユーザー',
    'nav.products': '製品',
    'nav.analytics': '分析',
    'nav.blogs': 'ブログ',
    'nav.tickets': 'チケット',
    
    // Hero
    'hero.badge': 'プレミアムジュエリー＆記念品',
    'hero.title.line1': 'ジュエリー。',
    'hero.title.line2': '記念品。',
    'hero.title.line3': '物語。',
    'hero.description': '思い出とつながりを祝う意味のあるアイテムのためのキュレーションされた空間。',
    'hero.cta.getStarted': '始めましょう',
    'hero.cta.consultation': '相談予約',
    'hero.stats.customers': '満足顧客',
    'hero.stats.experience': '年の経験',
    'hero.stats.award': '受賞歴',
    'hero.stats.design': 'デザイン優秀賞',
    'hero.price.from': '開始価格',
    
    // Authentication
    'auth.login': 'サインイン',
    'auth.loginDescription': 'Lunovaアカウントにサインイン',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.rememberMe': 'ログイン状態を保持',
    'auth.forgotPassword': 'パスワードを忘れましたか？',
    'auth.loggingIn': 'サインイン中...',
    'auth.noAccount': 'アカウントをお持ちでないですか？',
    'auth.signUp': 'サインアップ',
    'auth.signUpDescription': 'Lunovaに参加するために新しいアカウントを作成',
    'auth.createAccount': 'アカウント作成',
    'auth.registerDescription': '今日からLunovaファミリーに参加',
    'auth.name': 'フルネーム',
    'auth.confirmPassword': 'パスワード確認',
    'auth.creating': 'アカウント作成中...',
    'auth.alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
    'auth.resetPassword': 'パスワードリセット',
    'auth.resetPasswordDescription': 'メールアドレスを入力すると、パスワードリセットのリンクを送信します',
    'auth.sendResetLink': 'リセットリンクを送信',
    'auth.sending': '送信中...',
    'auth.resetEmailSent': 'パスワードリセットメールを送信しました。受信トレイをご確認ください。',
    'auth.backToLogin': 'ログインに戻る',
    'auth.emailPlaceholder': 'メールアドレスを入力',
    'auth.passwordPlaceholder': 'パスワードを入力',
    'auth.fullNamePlaceholder': 'フルネームを入力',
    'auth.confirmPasswordPlaceholder': 'パスワードを確認',
    'auth.accountOptions': 'アカウントオプション',
    'auth.forgotPasswordDescription': 'メールアドレスを入力するとパスワードリセットリンクを送信します',
    'auth.secureLogin': 'Supabaseで安全にログイン',
    'auth.loginFailed': 'ログインに失敗しました。認証情報を確認してください。',
    'auth.unexpectedError': '予期しないエラーが発生しました。もう一度お試しください。',
    'auth.fieldsRequired': 'すべてのフィールドが必要です。',
    'auth.signIn': 'サインイン',
    'auth.signingIn': 'サインイン中...',
    'auth.login.title': 'おかえりなさい',
    'auth.login.subtitle': 'アカウントにサインインして続行',
    
    // Dashboard
    'dashboard.create': '成功する',
    'dashboard.dashboard': 'ダッシュボード',
    'dashboard.welcome': 'おかえりなさい',
    'dashboard.subtitle': 'ジュエリーコレクションと注文を管理',
    'dashboard.logout': 'ログアウト',
    'dashboard.stats.orders': '総注文数',
    'dashboard.stats.favorites': 'お気に入り',
    'dashboard.stats.cart': 'カート商品',
    'dashboard.recentOrders': '最近の注文',
    'dashboard.orderDate': '注文日',
    'dashboard.newOrder': '新規注文',
    'dashboard.favorites': 'お気に入り',
    'dashboard.profile': 'プロフィール',
    'dashboard.settings': '設定',
    'dashboard.userManagement': 'ユーザー管理',
    'dashboard.users': 'ユーザー',
    'dashboard.searchUsers': 'ユーザーを検索...',
    'dashboard.sortingBy': '並び替え',
    'dashboard.filters': 'フィルター',
    'dashboard.userName': 'ユーザー名',
    'dashboard.emailAddress': 'メールアドレス',
    'dashboard.city': '都市',
    'dashboard.createdAt': '作成日',
    'dashboard.actions': 'アクション',
    'dashboard.previous': '前へ',
    'dashboard.next': '次へ',
    'dashboard.stats.activeUsers': 'アクティブユーザー',
    'dashboard.stats.newUsers': '新規ユーザー',
    'dashboard.stats.totalUsers': '総ユーザー数',
    'dashboard.stats.comparedTo': '先月比',
    'dashboard.products.title': '製品',
    'dashboard.products.items': 'アイテム',
    'dashboard.products.allShops': '全てのショップ',
    'dashboard.products.searchProducts': '製品を検索...',
    'dashboard.products.addProduct': '製品を追加',
    'dashboard.products.editProduct': '製品を編集',
    'dashboard.products.productName': '製品名',
    'dashboard.products.category': 'カテゴリー',
    'dashboard.products.price': '価格',
    'dashboard.products.stock': '在庫',
    'dashboard.products.status': 'ステータス',
    'dashboard.products.showing': '表示中',
    'dashboard.products.to': 'から',
    'dashboard.products.of': 'の',
    'dashboard.products.results': '結果',
    'dashboard.products.inStock': '在庫あり',
    'dashboard.products.lowStock': '在庫僅少',
    'dashboard.products.outOfStock': '在庫切れ',
    'dashboard.products.noProducts': '製品がありません。最初の製品を作成しましょう！',
    'dashboard.products.noProductsFound': '検索に一致する製品が見つかりませんでした。',
    'dashboard.products.createProductDescription': '新しい製品を作成するための詳細を入力してください。',
    'dashboard.products.editProductDescription': '以下の製品情報を更新してください。',
    'dashboard.products.selectShop': 'ショップを選択',
    'dashboard.products.selectShopPlaceholder': 'ショップを選択...',
    'dashboard.products.name': '製品名',
    'dashboard.products.description': '説明',
    'dashboard.products.pricing': '価格設定',
    'dashboard.products.salePrice': 'セール価格',
    'dashboard.products.additionalDetails': '追加詳細',
    'dashboard.products.subcategory': 'サブカテゴリー',
    'dashboard.products.material': '素材',
    'dashboard.products.physicalAttributes': '物理的特性',
    'dashboard.products.weight': '重量 (g)',
    'dashboard.products.dimensions': '寸法',
    'dashboard.products.inventory': '在庫',
    'dashboard.products.stockQuantity': '在庫数量',
    'dashboard.products.productFlags': '製品フラグ',
    'dashboard.products.isFeatured': '注目',
    'dashboard.products.isNew': '新着',
    'dashboard.products.isOnSale': 'セール中',
    'dashboard.errorFetchingProducts': '製品の取得中にエラーが発生しました。後でもう一度お試しください。',
    'dashboard.errorSavingProduct': '製品の保存中にエラーが発生しました。後でもう一度お試しください。',
    'dashboard.errorDeletingProduct': '製品の削除中にエラーが発生しました。後でもう一度お試しください。',
    'dashboard.confirmDeleteProduct': 'この製品を削除してもよろしいですか？',
    'dashboard.selectShop': 'この製品のショップを選択してください',
    'dashboard.tickets.title': 'サポートチケット',
    'dashboard.tickets.items': 'チケット',
    'dashboard.tickets.searchTickets': 'チケットを検索...',
    'dashboard.tickets.createTicket': 'チケットを作成',
    'dashboard.tickets.ticketId': 'チケットID',
    'dashboard.tickets.subject': '件名',
    'dashboard.tickets.customer': '顧客',
    'dashboard.tickets.status': 'ステータス',
    'dashboard.tickets.priority': '優先度',
    'dashboard.tickets.created': '作成日',
    'dashboard.tickets.updated': '更新日',
    'dashboard.tickets.showing': '表示中',
    'dashboard.tickets.to': 'から',
    'dashboard.tickets.of': 'の',
    'dashboard.tickets.results': '結果',
    'dashboard.loading': 'ローディング...',
    'dashboard.error': 'エラー',
    'dashboard.success': '成功',
    'dashboard.warning': '警告',
    'dashboard.info': '情報',
    'dashboard.filter': 'フィルター',
    'dashboard.totalShops': 'ショプ',
    'dashboard.totalProducts': '製品',
    'dashboard.shopLocation': '場所',
    'dashboard.shopCreated': '作成日',
    'dashboard.shopUpdated': '更新日',
    
    // Shop Management
    'nav.shops': 'ショップ',
    'dashboard.shops': 'ショップ管理',
    'dashboard.createShop': 'ショップを作成',
    'dashboard.editShop': 'ショップを編集',
    'dashboard.deleteShop': 'ショップを削除',
    'dashboard.shopName': 'ショップ名',
    'dashboard.shopDescription': '説明',
    'dashboard.shopContact': '連絡先',
    'dashboard.shopAddress': '住所',
    'dashboard.shopBusinessHours': '営業時間',
    'dashboard.shopSocialMedia': 'ソーシャルメディア',
    'dashboard.shopVerified': '認証済み',
    'dashboard.shopOwner': 'オーナー',
    'dashboard.shopCreatedAt': '作成日',
    'dashboard.shopUpdatedAt': '更新日',
    'dashboard.searchShops': 'ショップを検索...',
    'dashboard.noShopsFound': 'ショップが見つかりません',
    'dashboard.confirmDeleteShop': 'このショップを削除してもよろしいですか？',
    'dashboard.shopDeleted': 'ショップが正常に削除されました',
    'dashboard.shopDeleteError': 'ショップの削除中にエラーが発生しました',
    'dashboard.verificationStatus': '認証状況',
    
    // Market Insights
    'dashboard.marketInsights': '市場洞察',
    'dashboard.marketInsights.marketSize': '市場規模',
    'dashboard.marketInsights.growthRate': '成長率',
    'dashboard.marketInsights.keyPlayers': '主要企業',
    'dashboard.marketInsights.recentDevelopments': '最近の動向',
    'dashboard.marketInsights.consumerInsights': '消費者洞察',
    'dashboard.marketInsights.averagePrice': '平均価格',
    'dashboard.marketInsights.priceTrend': '価格傾向',
    'dashboard.marketInsights.error': '市場洞察の読み込みに失敗しました。後でもう一度お試しください。',
    'dashboard.marketInsights.noInsights': '洞察が利用できません。カテゴリを選択してください。',
    'dashboard.marketInsights.categories.jewelry': 'ジュエリー',
    'dashboard.marketInsights.categories.gasoline': 'ガソリン',
    'dashboard.marketInsights.categories.electronics': '電子機器',
    'dashboard.marketInsights.categories.fashion': 'ファッション',
    'dashboard.marketInsights.categories.homeDecor': 'ホームデコレーション',
    'common.loading': '読み込み中...',
    'common.refresh': '更新',
    'dashboard.verified': '認証済み',
    'dashboard.unverified': '未認証',
    'dashboard.cancel': 'キャンセル',
    'dashboard.saveChanges': '変更を保存',
    'dashboard.createShopDescription': 'ショップ情報を入力してください',
    'dashboard.editShopDescription': 'ショップ情報を編集してください',
    'dashboard.basicInformation': '基本情報',
    'dashboard.media': 'メディア',
    'dashboard.logoUrl': 'ロゴURL',
    'dashboard.bannerUrl': 'バナーURL',
    'dashboard.contactInformation': '連絡先情報',
    'dashboard.contactEmail': 'メール',
    'dashboard.phone': '電話番号',
    'dashboard.noContactInfo': '連絡先情報なし',
    'dashboard.streetAddress': '住所',
    'dashboard.state': '都道府県',
    'dashboard.country': '国',
    'dashboard.postalCode': '郵便番号',
    'dashboard.website': 'ウェブサイト',
    'dashboard.created': '作成日',
    'dashboard.errorDeletingShop': 'ショップの削除中にエラーが発生しました。後でもう一度お試しください。',
    'dashboard.errorSavingShop': 'ショップの保存中にエラーが発生しました。後でもう一度お試しください。',
    
    // Settings Modal
    'settings.title': '設定',
    'settings.general': '一般',
    'settings.account': 'アカウント',
    'settings.notifications': '通知',
    'settings.privacy': 'プライバシー',
    'settings.appearance': '外観',
    'settings.language': '言語',
    'settings.autoSave': '自動保存',
    'settings.analytics': '分析情報を共有',
    'settings.changePassword': 'パスワードを変更',
    'settings.twoFactor': '二要素認証',
    'settings.connectedAccounts': '接続済みアカウント',
    'settings.emailNotifications': 'メール通知',
    'settings.pushNotifications': 'プッシュ通知',
    'settings.marketingEmails': 'マーケティングメール',
    'settings.dataSaving': 'データ節約',
    'settings.cookies': 'Cookieの設定',
    'settings.dataExport': 'データのエクスポート',
    'settings.darkMode': 'ダークモード',
    'settings.theme': 'テーマ',
    
    // Services
    'services.title': '私たちのサービス',
    'services.description': 'カスタムデザインから専門的な修理まで、あなたのビジョンを実現し、貴重な作品を維持するための包括的なジュエリーサービスを提供します。',
    'services.custom.title': 'カスタムジュエリーデザイン',
    'services.custom.description': '熟練の職人があなたのビジョンに合わせたユニークな作品を作成します。',
    'services.custom.feature1': '3Dデザインプレビュー',
    'services.custom.feature2': '素材選択',
    'services.custom.feature3': '生涯保証',
    'services.restoration.title': 'ジュエリー修復',
    'services.restoration.description': 'プロの修復で大切な作品に新しい命を吹き込みます。',
    'services.restoration.feature1': 'アンティーク修復',
    'services.restoration.feature2': '石の交換',
    'services.restoration.feature3': '金属再仕上げ',
    'services.repair.title': '修理サービス',
    'services.repair.description': 'ジュエリーを完璧な状態に保つ専門修理サービス。',
    'services.repair.feature1': 'リングサイズ調整',
    'services.repair.feature2': 'チェーン修理',
    'services.repair.feature3': '留め具交換',
    'services.wedding.title': 'ウェディングコレクション',
    'services.wedding.description': '特別な瞬間には特別なジュエリーを。',
    'services.wedding.feature1': '婚約指輪',
    'services.wedding.feature2': '結婚指輪',
    'services.wedding.feature3': 'ブライダルセット',
    'services.luxury.title': 'ラグジュアリーピース',
    'services.luxury.description': '最も目の肥えたお客様のための高級ジュエリー。',
    'services.luxury.feature1': '貴石',
    'services.luxury.feature2': 'プラチナセッティング',
    'services.luxury.feature3': '認定証明書',
    'services.souvenirs.title': 'ユニーク記念品',
    'services.souvenirs.description': '特別な機会のための思い出に残る記念品とギフト。',
    'services.souvenirs.feature1': 'パーソナル彫刻',
    'services.souvenirs.feature2': 'ギフト包装',
    'services.souvenirs.feature3': 'カスタムボックス',
    
    // Collections
    'collections.title': '私たちのコレクション',
    'collections.description': '卓越した職人技と時代を超越したデザインで、それぞれが独自の物語を語る厳選されたコレクションをご覧ください。',
    'collections.diamond.title': 'ダイヤモンドエレガンス',
    'collections.diamond.description': '永遠の美しさを捉えた時代を超越したダイヤモンド作品',
    'collections.pearl.title': 'パールクラシック',
    'collections.pearl.description': '現代女性のための洗練されたパールジュエリー',
    'collections.gold.title': 'ゴールドヘリテージ',
    'collections.gold.description': '伝統的な職人技による手作りゴールド作品',
    'collections.modern.title': 'モダンミニマリスト',
    'collections.modern.description': '日常使いのためのクリーンラインと現代的デザイン',
    'collections.vintage.title': 'ヴィンテージトレジャー',
    'collections.vintage.description': '歴史を持つ厳選されたヴィンテージ作品',
    'collections.custom.title': 'カスタムクリエーション',
    'collections.custom.description': 'あなただけのためにデザインされたオーダーメイドジュエリー',
    'collections.view': 'コレクションを見る',
    'collections.viewAll': 'すべてのコレクションを見る',
    'collections.from': '開始価格',
    
    // Pricing
    'pricing.title': 'プランを選択',
    'pricing.description': 'ジュエリー愛好家でもビジネスオーナーでも、あなたのニーズに合った完璧なプランをご用意しています。',
    'pricing.forBuyers': '購入者向け',
    'pricing.forShopOwners': 'ショップ向け',
    'pricing.basic.name': 'ベーシックエクスプローラー',
    'pricing.basic.description': 'ジュエリーの発見と試着に最適',
    'pricing.premium.name': 'プレミアムコレクター',
    'pricing.premium.description': '本格的なジュエリー愛好家に理想的',
    'pricing.business.name': 'ビジネスプロ',
    'pricing.business.description': 'ジュエリービジネスのための完全ソリューション',
    'pricing.enterprise.name': 'エンタープライズスケール',
    'pricing.enterprise.description': '大規模ジュエリーチェーンのための高度なソリューション',
    'pricing.popular': '最も人気',
    'pricing.perPiece': '作品あたり',
    'pricing.getStarted': '始める',
    'pricing.bulkQuote': '大量注文のカスタム見積もりが必要ですか？',
    'pricing.contactSales': '営業チームにお問い合わせ',
    
    // Testimonials
    'testimonials.title': 'お客様の声',
    'testimonials.description': '私たちの言葉だけでなく、Lunovaの体験について満足されたお客様の声をお聞きください。',
    'testimonials.rating': '平均評価',
    'testimonials.reviews': 'レビュー',
    'testimonials.satisfaction': '満足度',
    
    // Contact
    'contact.title': 'お問い合わせ',
    'contact.description': '美しいものを作る準備はできていますか？あなたのビジョンについて話し合い、夢のジュエリーを実現しましょう。',
    'contact.info': '連絡先情報',
    'contact.visit': 'ショールーム訪問',
    'contact.call': 'お電話',
    'contact.email': 'メール',
    'contact.hours': '営業時間',
    'contact.schedule': '相談予約',
    'contact.scheduleDesc': '専門デザイナーとのプライベート相談を予約して、プロジェクトについて詳しく話し合いましょう。',
    'contact.bookAppointment': '予約する',
    'contact.sendMessage': 'メッセージを送る',
    'contact.form.name': 'お名前',
    'contact.form.email': 'メールアドレス',
    'contact.form.phone': '電話番号',
    'contact.form.service': 'サービス',
    'contact.form.message': 'メッセージ',
    'contact.form.messagePlaceholder': 'プロジェクトについてお聞かせください...',
    'contact.form.send': 'メッセージを送信',
    'contact.form.selectService': 'サービスを選択',
    'contact.form.customDesign': 'カスタムデザイン',
    'contact.form.restoration': '修復',
    'contact.form.repair': '修理',
    'contact.form.consultation': '相談',
    
    // Footer
    'footer.description': '1998年以来、時代を超越したジュエリーと貴重な思い出を創造しています。すべての作品が物語を語り、情熱と精密さで作られています。',
    'footer.quickLinks': 'クイックリンク',
    'footer.services': 'サービス',
    'footer.contactInfo': '連絡先情報',
    'footer.newsletter': 'ニュースレター',
    'footer.newsletterPlaceholder': 'メールアドレス',
    'footer.copyright': '© 2025 Lunova Co. All rights reserved.',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.shipping': '配送・返品'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      currentLanguage: language, 
      setLanguage, 
      changeLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};